# Generated by Django 4.1.2 on 2022-10-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Картинка готового блюда', null=True, upload_to='backend/media/', verbose_name='recipe image'),
        ),
    ]
