# Generated by Django 4.1.2 on 2022-10-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_favorite_recipe_alter_favorite_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Картинка готового блюда', null=True, upload_to='', verbose_name='recipe image'),
        ),
    ]
